In [5]:
import numpy as np
grid = [[0,3,0,4,0,5,0,7,0],
        [6,2,0,0,8,0,4,0,0],
        [7,0,0,0,0,1,0,0,9],
        [2,0,6,0,0,3,8,0,0],
        [0,0,0,0,0,0,2,0,3],
        [0,1,3,6,0,0,9,5,0],
        [0,0,8,0,4,7,0,0,0],
        [0,0,0,0,0,0,0,0,6],
        [0,0,0,0,5,0,3,0,0]]


In [6]:
def is_possible(guess:int ,row,col):
    global grid
    for c in range(9):
        if grid[row][c] == guess:
            return False
    for r in range(9):
        if grid[r][col] == guess :
            return False
    x = (row//3)*3
    y = (col//3)*3
    for i in range(3):
        for j in range(3):
            if grid[x+i][y+j] == guess :
                return False
    return True

for i in range(1,10):
    print(i,":",is_possible(i,7,7))


1 : True
2 : True
3 : False
4 : True
5 : False
6 : False
7 : False
8 : True
9 : True


In [7]:
def solve():
    global grid
    for r in range(9):
        for c in range(9):
            if grid[r][c] == 0:
                for guess in range(1,10):
                    if is_possible(guess,r,c) :
                        grid[r][c] = guess
                        solve()
                        grid[r][c] = 0
                return
    print(np.matrix(grid))
    input("More?")
    
solve()

[[1 3 9 4 2 5 6 7 8]
 [6 2 5 7 8 9 4 3 1]
 [7 8 4 3 6 1 5 2 9]
 [2 4 6 5 9 3 8 1 7]
 [5 9 7 8 1 4 2 6 3]
 [8 1 3 6 7 2 9 5 4]
 [3 6 8 2 4 7 1 9 5]
 [9 5 2 1 3 8 7 4 6]
 [4 7 1 9 5 6 3 8 2]]
More?
[[1 3 9 4 2 5 6 7 8]
 [6 2 5 7 8 9 4 3 1]
 [7 8 4 3 6 1 5 2 9]
 [2 4 6 5 9 3 8 1 7]
 [9 5 7 8 1 4 2 6 3]
 [8 1 3 6 7 2 9 5 4]
 [3 6 8 2 4 7 1 9 5]
 [5 9 2 1 3 8 7 4 6]
 [4 7 1 9 5 6 3 8 2]]
More?
[[8 3 9 4 6 5 1 7 2]
 [6 2 1 7 8 9 4 3 5]
 [7 4 5 2 3 1 6 8 9]
 [2 9 6 5 7 3 8 1 4]
 [5 8 7 1 9 4 2 6 3]
 [4 1 3 6 2 8 9 5 7]
 [9 6 8 3 4 7 5 2 1]
 [3 5 4 8 1 2 7 9 6]
 [1 7 2 9 5 6 3 4 8]]
More?
[[8 3 9 4 6 5 1 7 2]
 [6 2 1 7 8 9 4 3 5]
 [7 5 4 2 3 1 6 8 9]
 [2 9 6 5 7 3 8 1 4]
 [5 8 7 1 9 4 2 6 3]
 [4 1 3 6 2 8 9 5 7]
 [9 6 8 3 4 7 5 2 1]
 [3 4 5 8 1 2 7 9 6]
 [1 7 2 9 5 6 3 4 8]]
More?
[[9 3 1 4 2 5 6 7 8]
 [6 2 5 7 8 9 4 3 1]
 [7 8 4 3 6 1 5 2 9]
 [2 4 6 5 9 3 8 1 7]
 [5 7 9 8 1 4 2 6 3]
 [8 1 3 6 7 2 9 5 4]
 [3 6 8 2 4 7 1 9 5]
 [1 5 2 9 3 8 7 4 6]
 [4 9 7 1 5 6 3 8 2]]
More?
[[9 3 1 4 2 5 6 7 8]

In [71]:
def rec(n):
    if n<= 0:
        print("yahoo")
        return n 
    print("Here : ",n)
    rec(n-1)
    print("Here again : ",n)
    
rec(10)

Here :  10
Here :  9
Here :  8
Here :  7
Here :  6
Here :  5
Here :  4
Here :  3
Here :  2
Here :  1
yahoo
Here again :  1
Here again :  2
Here again :  3
Here again :  4
Here again :  5
Here again :  6
Here again :  7
Here again :  8
Here again :  9
Here again :  10
